[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x']

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "cd client && npm install && npm run build"
]

[start]
cmd = "uvicorn server.main:app --host 0.0.0.0 --port $PORT"
